### PR TITLE
Fix "No newline at end of file" issue

### PR DESCRIPTION
**Pull request by dotansimha**

### CODE REVIEW

**Comment by stubailo** [comment]
Can you add a  test? Also, I'm worried about replacing it with a blank line - does that mean there is some blank line in the output somewhere?

**Comment by stubailo** [comment]
@dotansimha I mean a blank line in the output of this NPM package, rather than the view component.

**Comment by dotansimha** [comment]
@stubailo 
I that better? I completly removed the line and added a new patch file with the new line message and tests for this case

**Comment by dotansimha** [comment]
@stubailo Just a reminder...
Thanks

**Comment by stubailo** [comment]
Merged: 8dbd9c0b611b48f6d92609fbea46b5b57468b03f

Published at 0.2.1

Sorry for the delay!

**Pull request closed without merging**
